prost-amino-derive: fix `_prost` reference (#3)
This was inadvertently changed here:

https://github.com/informalsystems/amino_rs/pull/1/files#diff-c1c0205a34afb85e1afdf69f9b03d9d1R98-R110

It's causing the custom derive to fail:

```
   Compiling tendermint v0.14.0 (/Users/bascule/src/tendermint-rs/tendermint)
error[E0433]: failed to resolve: could not find `prost` in `{{root}}`
  --> tendermint/src/amino_types/block_id.rs:11:28
   |
11 | #[derive(Clone, PartialEq, Message)]
   |                            ^^^^^^^ could not find `prost` in `{{root}}`
```